# -*- coding: utf-8 -*-
"""LAB1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYWxcJOO044NBgHsqLsAEULsHsDnXNKp
"""

#problem3 
num1= float(input('Enter your first number : '))
num2= float(input('Enter your second number : '))

if (num1==num2):
    print("The numbers are equal")
elif (num1>num2):
    print("First is greater")
else:
    print("Second is greater")

#problem4
num1= float(input('Number 1 :'))
num2= float(input('Number 2 :'))

if (num1>num2):
    print(num1-num2)
elif (num2>num1):
    print(num2-num1)

else:
    print()

#problem5

num1= float(input('Enter a number : '))


if (num1%2==0):
    print('The number is even')
else:
    print('The number is odd')

#problem6

num1= int(input('Enter a number : '))

#if (num1%2==0 and num1%5==0):
    #print('multiples of 2 and 5 both')
if (num1%2==0):
    print(num1)
elif (num1%5==0):
    print(num1)
    

else:
    print('Not a multiple of 2 OR 5')

#problem7

num1= int(input('Enter a number : '))

if (num1%2==0 and num1%5==0):
    print('multiples of 2 and 5 both')
elif (num1%2==0):
    print(num1)
elif (num1%5==0):
    print(num1)
    

else:
    print('Not a multiple we want')

#problem8

num1= int(input('Enter a number : '))

if (num1%2==0 and num1%5==0):
    print(num1)
    

else:
    print("Not multiple of 2 and 5 both")

#problem9

num1= int(input('Enter second : '))

hour= num1//3600
num2= num1%3600 
mins= num2//60
sec= num2%60

print ('Hour :',hour , 'Minutes :',mins , 'Seconds :',sec )

#problem10

hour= int(input('Enter hour : '))

if (hour<=40 and hour>=0):
    print(hour*200)
elif (hour>168):
    print('Impossible to work more than 168 hours weekly')
elif (hour>40):
    print(8000+(hour-40)*300)

else:
    print('hour cannot  be negative')

#problem11
numb= int(input('Enter value of S : '))
eq1= 4+numb**2/14900

if (numb<100):
    print(3000-125*numb**2)
elif (numb>=100):
    print(12000/eq1)
else:
    pass

#problem12

hour = int(input('Time: '))

if (0<=hour and 23>=hour ):
    if ((hour>=0 and hour<=3) or (hour>=7 and hour<=11) or (hour>=14 and hour<=15) or (hour==18) or (hour>=21 and hour<=23)):
        print('Patience is a virtue')
    elif (hour>3 and hour<7):
        print('Breakfast')
    elif (hour>11 and hour<14):
        print('Lunch')
    elif (hour>15 and hour<18):
        print('Snacks')
    elif (hour==19 or hour==20):
        print('Dinner')
    else:
        ('Wrong time')
else:
    print('Wrong time')

#problem13
marks = int(input(' Enter Your marks: '))

if (marks>=0 and marks<=100):
    if(marks>=90):
        print('A')
    elif(marks>=80 and marks<=89):
        print('B')
    elif(marks>=70 and marks<=79):
        print('C')
    elif(marks>=60 and marks<=69):
        print('D')
    elif(marks>=50 and marks<=59):
        print('E')
    else:
        print('F')
else:
    print('Invalid number')

#problem14

meters= int(input('Enter your distance in meter : '))
seconds= int(input('Enter your time in second :'))

km= meters/1000
hour= seconds/3600
kmh= km/hour
print(kmh, 'km/h')
if (kmh<60):
    print('Too slow. Needs more changes')
elif (kmh>=60 and kmh<=90):
    print('Velocity is okay. The car is ready!')
elif (kmh>90):
    print ( 'Too fast. Only a few changes should suffice')
    
else:
    pass

#problem15
cgpa= float(input('Your CGPA: '))
credit = int(input('Total credit completed: '))


if (credit>=30):
    if(cgpa==4.00):
        print('The student is eligible for a waiver of 100 percent')
    elif(cgpa>=3.95 and cgpa<=3.99):
        print('The student is eligible for a waiver of 75 percent')
    elif(cgpa>=3.90 and cgpa<=3.94):
        print('The student is eligible for a waiver of 50 percent')
    elif(cgpa>=3.80 and cgpa<=3.89):
        print('The student is eligible for a waiver of 25 percent')
    #elif(cgpa>=3.80 and cgpa<=3.84):
        #print('The student is eligible for a waiver of  percent')
    else:

        print('The student is not eligible for a waiver')
    
else:
    print('The student is not eligible for a waiver')

p = 5
q = 6
r = 9
sum = 0
if (p < 12):
    print(r + 2)
else:
    print(r + p)
if (q > 20):
    print(r + 19)
elif (q <= 6):
    print(q + 3)
else:
    print(p + q + r)
if (r > 15):
    print(r)
elif (r == 0):
    print(p + q)
else:
    print(p)
if (sum != 0):
    print(3)
else:
    print(sum + 32)
if (p>0 and r<10):
    print(p+r)
else:
    print(p-r)