# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tlp7iKfFSIr_c39IVwmS8BiFf3wXkauq
"""

#task1A #DONE

a= 30

while a>-6:
    a-=6
    
    if a==-6:
        print(a)
    else:
        print(a, end=',')

#task1B #DONE

for i in range(-10,21,5):
    if i==20:
        print(i)
    else:
        print(i, end=',')

#task1C #DONE

for i in range(18,64,9):
    
    if i==63:
        print(i)
    else:
        print(i, end=',')

#task1D #DONE
i= 1
v= 18

while v<=63:
    print(i*v, end=',')
    v+=9
    i*=-1

#task2 #DONE

car= input('car name: ')
num1= int(input('number: '))

while (num1>0):
    print(car)
    num1-=1

#task3

num1= 0
count= 0
while num1<601:
    num1+=1
    if num1%7==0 and num1%9==0:
        count+=num1
print(count)

sum=0
for i in range(1,601):
    if i%7==0 and i%9==0:
        sum+=i
        
print(sum)

#task4 #incomplete

num1= 0
count= 0
while num1<601:
    num1+=1
    if num1%7==0 and num1%9==0:
        continue
    count+=num1
print(count)

#task4 #DONE

sum=0
for i in range(1,601):
    if i%7==0 and i%9==0:
        continue
    if i%7==0 or i%9==0:
        sum+=i
print(sum)

#task5 #DONE

count= 9
while count%2!=0:
    count+=2
    if count==51:
        break
    print(count)

#Task6 

n= int(input('n: '))
sum=0 #55

for i in range(1,n+1):
    if i%2==0:
        sum-=i**2
    elif i%2!=0:
        sum+=i**2
    
print(sum)

n= int(input('n: '))
sum=0 
count=1
while count<=n:
    if count%2!=0:
        sum+=count**2
    elif count%2==0:
        sum-=count**2
    count+=1
print(sum)

#task7 #DONE

count= 1
sum= 0
v= 0
while count<11: 
    i= int(input('Enter '))
    count+=1
    if i%2!=0:
        sum+=i
        v+=1
print('The total of the odd numbers is',sum,' and their average is',sum/v)

#task8 #DONE
n= int(input('Enter: '))
sum=0
for i in range(0,n+1,7):
    sum+=i
print(sum)

#task9 #DONE

count=0
sum=0

while count<5:
    n= int(input('Enter: '))
    count+=1
    sum+=n
    print(sum)

#TASK10 #DONE

num1= int(input('Enter a number: '))
count= 0

while 1:
    i=num1%10 
    num1//=10
    
    if num1==0:
        print(i)
        break
    else:
        print(i, end=", ")

#task11 #DONE

n= int(input('Enter a number: '))

count=0
while 1:
    n//=10
    count+=1
    if n==0:
        break
print(count)

#task12

#task13

n= int(input('Enter a number: '))
sum=0
for i in range(1,int(n)+1):
    
    if n%i==0:
        print(i, end=',')
        sum+=1
print('Total',sum,'divisors')

#TASK14 #DONE
v= int(input("number "))
count=1
sum=0
while count<v:
    if v%count==0:
        sum+=count
        
    count+=1
if sum==v:
    print(sum,'Perfect')
else:
    print(sum,'Not Perfect')

